import React from "react";
import { Autocomplete } from "@material-ui/lab"
import { TextField, makeStyles } from "@material-ui/core";

const useStyles = makeStyles({
  root: {
    width: 300,
  },
});

const ScrollableCombobox = () => {
  const classes = useStyles();
  return <Autocomplete
    open
    options={spells}
    style={{ width: 300 }}
    ListboxProps={{
      "data-simplebar": true,
      "data-simplebar-auto-hide": false,
    }}
    renderInput={params => (
      <TextField {...params} classes={{ ...params.classes, root: classes.root }} variant="outlined" fullWidth />
    )}
  />
};

export default ScrollableCombobox;

const spells = [
  "Dia",
  "Cure",
  "Stone",
  "Poison",
  "Barstone",
  "Paralyze",
  "Protect",
  "Barsleep",
  "Blind",
  "Water",
  "Barwater",
  "Barpoison",
  "Bio",
  "Blind",
  "Barparalyze",
  "Aquaveil",
  "Baraero",
  "Slow",
  "Cure II",
  "Aero",
  "Deodorize",
  "Diaga",
  "Enthunder",
  "Shell",
  "Barfire",
  "Silence",
  "Barblind",
  "Enstone",
  "Fire",
  "Blaze Spikes",
  "Enaero",
  "Sneak",
  "Regen",
  "Gravity",
  "Barblizzard",
  "Enblizzard",
  "Barsilence",
  "Blink",
  "Blizzard",
  "Enfire",
  "Sleep",
  "Barthunder",
  "Invisible",
  "Cure III",
  "Protect II",
  "Enwater",
  "Thunder",
  "Dia II",
  "Dispel",
  "Phalanx",
  "Stoneskin",
  "Stone II",
  "Distract",
  "Bio II",
  "Shell II",
  "Raise",
  "Barvirus",
  "Water II",
  "Ice Spikes",
  "Refresh",
  "Frazzle",
  "Barpetrify",
  "Aero II",
  "Poison II",
  "Sleep II",
  "Protect III",
  "Cure IV",
  "Flurry",
  "Haste",
  "Fire II",
  "Enthunder II",
  "Enstone II",
  "Enaero II",
  "Blizzard II",
  "Enblizzard II",
  "Shell III",
  "Enfire II",
  "Thunder II",
  "Shock Spikes",
  "Enwater II",
  "Protect IV",
  "Stone III",
  "Water III",
  "Shell IV",
  "Aero III",
  "Fire III",
  "Blizzard III",
  "Thunder III",
  "Bio III",
  "Blind II",
  "Dia III",
  "Paralyze II",
  "Phalanx II",
  "Slow II",
  "Regen II",
  "Stone IV",
  "Protect V",
  "Baramnesia",
  "Water IV",
  "Gain-VIT",
  "Refresh II",
  "Addle",
  "Aero IV",
  "Gain-MND",
  "Fire IV",
  "Gain-CHR",
  "Shell V",
  "Break",
  "Blizzard IV",
  "Gain-AGI",
];